id: moderatorTriggers
name: GitOps.PullRequestIssueManagement
description: Defines the users and permissions for the Admin
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          # If the activity sender is any one of the moderators, has Admin permission on the repo, or has Write permissions on the repo. . .
          - or:
              - activitySenderHasPermission:
                  permission: Admin
              - activitySenderHasPermission:
                  permission: Write
          # If the payload is a Pull_Request_Review and an approval, add the Moderator-Approved label
          - if:
              - payloadType: Pull_Request_Review
              - isReviewState:
                  reviewState: Approved
            then:
              - addLabel:
                  label: Administrator-Approved
onFailure:
onSuccess: