id: automergeTriggers
name: GitOps.PullRequestIssueManagement
description: Handles enabling / disabling automerge
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Enable Auto Merge when the "Merge-Needed" label is present
        if:
          - payloadType: Pull_Request
          - hasLabel:
              label: Merge-Needed
        then:
          - removeLabel:
              label: Merge-Needed
          - addLabel:
              label: Policy-Accepted
          - enableAutoMerge:
              mergeMethod: Squash
onFailure:
onSuccess:
