name: Auto Assign
on:
  issues:
    types: [opened, reopened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Auto-assign issue
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.BOT }}
          teams: member
          removePreviousAssignees: true
          numOfAssignee: 3
