name: Sync To Gitee

on:
  schedule: [{cron: 0 * * * *}]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:CoolPlayLin/policy-work-team.git"
          destination-repo: "git@gitee.com:CoolPlayLin/policy-work-team"
